/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.formdev.flatlaf.FlatLightLaf;
import dao.UserLoginDAO;
import entity.User_Login;
import helper.AuthUser;
import helper.MsgHelper;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.Random;
import javax.swing.JLabel;

/**
 *
 * @author balis
 */
public class LoginJFrame extends javax.swing.JFrame {

    UserLoginDAO userLoginDAO = new UserLoginDAO();

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("OMEGAPAY");
    }

    //-------------- Sign in section -------------
    private void login() {
        String username = txtUserSignin.getText();
        String password = new String(txtPassSignin.getPassword());
        User_Login user = userLoginDAO.selectByID(username);
        if (!username.equalsIgnoreCase(user.getUsername()) || !password.equals(user.getPassword())) {
            MsgHelper.alert(this, "Wrong username or password!");
        } else {
            AuthUser.user = user;
            this.dispose();
            new GreetJDialog(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }

    private void openForgotPasswordOptions() {
        new EmailOrSMSJDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }

    //-------------- Sign up section -------------
    private void signup() {
        String username = txtUserSignup.getText();
        String password = new String(txtPassSignup.getPassword());
        String retype = new String(txtRetypeSignup.getPassword());
        User_Login user = getSignupForm();
        boolean isUserExist = (userLoginDAO.selectByID(username) != null);
        String error = "";
        if (isUserExist) {
            error += "Username is already exist!\n";
        } else if (username.equals("") || password.equals("") || retype.equals("")) {
            error += "Fields must not be empty!\n";
        } else if (username.length() < 6) {
            error += "Username length must longer than 6 letters!\n";
        } else if (password.length() < 8) {
            error += "Password length must longer than 8 letters!\n";
        } else if (!password.equals(retype)) {
            error += "Password and retype didn't match!\n";
        } else {
            try {
                userLoginDAO.insert(user);
                MsgHelper.alert(this, "Create account successfully!\n");
                this.dispose();
                new SignupDetailsJDialog(this, rootPaneCheckingEnabled, user.getOmegaAccount()).setVisible(true);
            } catch (Exception e) {
                error = "Unknown error has occured!\n";
            }
        }
        if (!error.equals("")) {
            MsgHelper.alert(this, error);
        }
    }

    private User_Login getSignupForm() {
        User_Login user = new User_Login();
        user.setOmegaAccount(generateOmegaAccount());
        user.setUsername(txtUserSignup.getText());
        user.setPassword(new String(txtPassSignup.getPassword()));
        return user;
    }

    // random omegaAccount voi do dai 12
    private String generateOmegaAccount() {
        return "" + (100000 + new Random().nextInt(900000)) + (100000 + new Random().nextInt(900000));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlSigninSection = new javax.swing.JPanel();
        txtUserSignin = new javax.swing.JTextField();
        txtPassSignin = new javax.swing.JPasswordField();
        btnSignin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkShowPass = new javax.swing.JCheckBox();
        lblWelcomeback = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        pnlSignupSection = new javax.swing.JPanel();
        txtUserSignup = new javax.swing.JTextField();
        txtRetypeSignup = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        chkShowPass2 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPassSignup = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        lblOmegaSymbol = new javax.swing.JLabel();
        lblOmegaTitle = new javax.swing.JLabel();
        pnlSignup = new javax.swing.JPanel();
        lblSign = new javax.swing.JLabel();
        pnlChangePassword = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setLayout(new java.awt.CardLayout());

        pnlSigninSection.setBackground(new java.awt.Color(255, 255, 255));
        pnlSigninSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserSignin.setText("To Minh Tri");
        txtUserSignin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserSigninKeyPressed(evt);
            }
        });
        pnlSigninSection.add(txtUserSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 256, 326, 36));

        txtPassSignin.setText("12345678");
        txtPassSignin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassSigninKeyPressed(evt);
            }
        });
        pnlSigninSection.add(txtPassSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 342, 326, 36));

        btnSignin.setBackground(new java.awt.Color(238, 0, 51));
        btnSignin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignin.setForeground(new java.awt.Color(255, 255, 255));
        btnSignin.setText("SIGN IN");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        pnlSigninSection.add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 445, 96, 36));

        jLabel1.setText("Username");
        pnlSigninSection.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 234, 85, -1));

        jLabel2.setText("Password");
        pnlSigninSection.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 320, 86, -1));

        chkShowPass.setText("Show password");
        chkShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPassActionPerformed(evt);
            }
        });
        pnlSigninSection.add(chkShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 390, 143, -1));

        lblWelcomeback.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcomeback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeback.setText(" WELCOME BACK");
        pnlSigninSection.add(lblWelcomeback, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 330, 33));
        pnlSigninSection.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 250, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Forgot password?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        pnlSigninSection.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 110, -1));

        pnlLeft.add(pnlSigninSection, "card2");

        pnlSignupSection.setBackground(new java.awt.Color(255, 255, 255));
        pnlSignupSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlSignupSection.add(txtUserSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 326, 36));
        pnlSignupSection.add(txtRetypeSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 326, 36));

        jButton3.setBackground(new java.awt.Color(238, 0, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SIGN UP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlSignupSection.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 445, 96, 36));

        jLabel6.setText("Username");
        pnlSignupSection.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 85, -1));

        jLabel10.setText("Retype password");
        pnlSignupSection.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 120, -1));

        chkShowPass2.setText("Show password");
        chkShowPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPass2ActionPerformed(evt);
            }
        });
        pnlSignupSection.add(chkShowPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 143, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SIGN UP");
        pnlSignupSection.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 330, 33));
        pnlSignupSection.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 250, 20));
        pnlSignupSection.add(txtPassSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 326, 36));

        jLabel11.setText("Password");
        pnlSignupSection.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 86, -1));

        pnlLeft.add(pnlSignupSection, "card3");

        pnlRight.setBackground(new java.awt.Color(238, 0, 51));

        lblOmegaSymbol.setBackground(new java.awt.Color(255, 255, 255));
        lblOmegaSymbol.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        lblOmegaSymbol.setForeground(new java.awt.Color(255, 255, 255));
        lblOmegaSymbol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOmegaSymbol.setText("Ω");

        lblOmegaTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblOmegaTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblOmegaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOmegaTitle.setText("OMEGAPAY");

        pnlSignup.setBackground(new java.awt.Color(238, 0, 51));
        pnlSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSignupMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlSignupMouseReleased(evt);
            }
        });

        lblSign.setBackground(new java.awt.Color(51, 255, 51));
        lblSign.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSign.setForeground(new java.awt.Color(255, 255, 255));
        lblSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSign.setText("SIGN UP");
        lblSign.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout pnlSignupLayout = new javax.swing.GroupLayout(pnlSignup);
        pnlSignup.setLayout(pnlSignupLayout);
        pnlSignupLayout.setHorizontalGroup(
            pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignupLayout.createSequentialGroup()
                .addComponent(lblSign, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSignupLayout.setVerticalGroup(
            pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignupLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(lblSign, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlChangePassword.setBackground(new java.awt.Color(238, 0, 51));
        pnlChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlChangePasswordMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(51, 255, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CHANGE PASSWORD");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout pnlChangePasswordLayout = new javax.swing.GroupLayout(pnlChangePassword);
        pnlChangePassword.setLayout(pnlChangePasswordLayout);
        pnlChangePasswordLayout.setHorizontalGroup(
            pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangePasswordLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlChangePasswordLayout.setVerticalGroup(
            pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChangePasswordLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlExit.setBackground(new java.awt.Color(238, 0, 51));
        pnlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExitMouseClicked(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(51, 255, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("EXIT");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExitLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExitLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblOmegaSymbol))
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblOmegaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblOmegaSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblOmegaTitle)
                .addGap(98, 98, 98)
                .addComponent(pnlSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPassActionPerformed
        if (chkShowPass.isSelected()) {
            txtPassSignin.setEchoChar((char) 0);
        } else {
            txtPassSignin.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowPassActionPerformed

    private void chkShowPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPass2ActionPerformed
        if (chkShowPass2.isSelected()) {
            txtPassSignup.setEchoChar((char) 0);
            txtRetypeSignup.setEchoChar((char) 0);
        } else {
            txtPassSignup.setEchoChar('*');
            txtRetypeSignup.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowPass2ActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        login();
    }//GEN-LAST:event_btnSigninActionPerformed

    private void pnlSignupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignupMouseReleased

    }//GEN-LAST:event_pnlSignupMouseReleased

    private void pnlSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignupMouseClicked
        if (pnlSigninSection.isVisible()) {
            lblSign.setText("SIGN UP");
            pnlSigninSection.setVisible(false);
            pnlSignupSection.setVisible(true);
        } else if (pnlSignupSection.isVisible()) {
            lblSign.setText("SIGN IN");
            pnlSigninSection.setVisible(true);
            pnlSignupSection.setVisible(false);
        }
    }//GEN-LAST:event_pnlSignupMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        signup();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtUserSigninKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserSigninKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtUserSigninKeyPressed

    private void txtPassSigninKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassSigninKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtPassSigninKeyPressed

    private void pnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pnlExitMouseClicked

    private void pnlChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChangePasswordMouseClicked
        this.dispose();
        new ChangePasswordJDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_pnlChangePasswordMouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        JLabel label = (JLabel) evt.getSource();
        label.setForeground(new Color(204, 255, 0));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        JLabel label = (JLabel) evt.getSource();
        label.setForeground(new Color(102, 255, 102));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        openForgotPasswordOptions();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignin;
    private javax.swing.JCheckBox chkShowPass;
    private javax.swing.JCheckBox chkShowPass2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblOmegaSymbol;
    private javax.swing.JLabel lblOmegaTitle;
    private javax.swing.JLabel lblSign;
    private javax.swing.JLabel lblWelcomeback;
    private javax.swing.JPanel pnlChangePassword;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlSigninSection;
    private javax.swing.JPanel pnlSignup;
    private javax.swing.JPanel pnlSignupSection;
    private javax.swing.JPasswordField txtPassSignin;
    private javax.swing.JPasswordField txtPassSignup;
    private javax.swing.JPasswordField txtRetypeSignup;
    private javax.swing.JTextField txtUserSignin;
    private javax.swing.JTextField txtUserSignup;
    // End of variables declaration//GEN-END:variables
}
