/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.formdev.flatlaf.FlatLightLaf;
import dao.UserDetailDAO;
import entity.User_Detail;
import helper.ImageHelper;
import helper.MsgHelper;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author balis
 */
public class SignupDetailsJDialog extends javax.swing.JDialog {

    UserDetailDAO userDetailDAO = new UserDetailDAO();
    static String omegaAccount;

    /**
     * Creates new form SignupDetailsJDialog
     */
    // Truyen tham so omegaAccount de tiep tuc insert UserDetail
    public SignupDetailsJDialog(javax.swing.JFrame parent, boolean modal, String omegaAccount) {
        super(parent, modal);
        this.omegaAccount = omegaAccount;
        initComponents();
        setLocationRelativeTo(parent);
    }

    private void insert() {
        if (isSignupFormValid()) {
            User_Detail entity = getUserDetailForm();
            userDetailDAO.insert(entity);
            MsgHelper.alert(this, "Insert successfully!");
            this.dispose();
            new LoginJFrame().setVisible(true);
        }
    }

    private boolean isSignupFormValid() {
        boolean isValid = true;
        String error = "";
        if (txtFirstname.getText().equals("")) {
            error += "First name can not be empty!\n";
            isValid = false;
        }
        if (txtLastname.getText().equals("")) {
            error += "Last name can not be empty!\n";
            isValid = false;
        }
        if (!txtEmail.getText().matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) {
            error += "Email is invalid!\n";
            isValid = false;
        }
        if (txtPhone.getText().length() < 10) {
            error += "Phone must have the length of 10!\n";
            isValid = false;
        }
        if (txtBirthday.getDate() == null) {
            error += "Birthday is invalid!\n";
            isValid = false;
        }
        if (txtAddress.getText().equals("")) {
            error += "Address can not be empty!\n";
            isValid = false;
        }
        if (!error.equals("")) {
            MsgHelper.alert(this, error);
        }
        return isValid;
    }

    private User_Detail getUserDetailForm() {
        User_Detail userDetail = new User_Detail();
        userDetail.setOmegaAccount(omegaAccount);
        userDetail.setFirstName(txtFirstname.getText());
        userDetail.setLastName(txtLastname.getText());
        userDetail.setEmail(txtEmail.getText());
        userDetail.setAddress(txtAddress.getText());
        userDetail.setBirthday(txtBirthday.getDate());
        userDetail.setDayCreated(new Date());
        userDetail.setPhone(txtPhone.getText());
        userDetail.setGender(rdoMale.isSelected());
        // cho mac dinh status rank la Silver, neu tk >50tr thi Gold, >100tr thi Platinum 
        userDetail.setStatus("Silver");
        // Cho so du tai khoan mac dich la 5.000.000 VND
        userDetail.setOmegaBalance(5000000F);
        // lay ten anh luu tam o toolTipText
        userDetail.setPhoto(lblPhoto.getToolTipText());
        return userDetail;
    }

    private void choosePhoto() {
        JFileChooser chooser = new JFileChooser(System.getProperty("user.home") + "/Desktop");
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            ImageHelper.saveFile(file);
            ImageIcon icon = ImageHelper.readFile(file.getName(), lblPhoto);
            lblPhoto.setToolTipText(file.getName());
            lblPhoto.setIcon(icon);
        }
    }

    private void openMain() {
        new MainJFrame().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JPanel();
        pnlUp = new javax.swing.JPanel();
        lblPersonalDetailTitle = new javax.swing.JLabel();
        pnlDown = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        txtFirstname = new javax.swing.JTextField();
        lblFirstname = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtBirthday = new com.toedter.calendar.JDateChooser();
        lblBirthday = new javax.swing.JLabel();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        lblGender = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        pnlUp.setBackground(new java.awt.Color(238, 0, 51));

        lblPersonalDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPersonalDetailTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPersonalDetailTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonalDetailTitle.setText("PERSONAL DETAILS");

        javax.swing.GroupLayout pnlUpLayout = new javax.swing.GroupLayout(pnlUp);
        pnlUp.setLayout(pnlUpLayout);
        pnlUpLayout.setHorizontalGroup(
            pnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(pnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUpLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblPersonalDetailTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlUpLayout.setVerticalGroup(
            pnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUpLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblPersonalDetailTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlDown.setBackground(new java.awt.Color(255, 255, 255));
        pnlDown.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhotoMouseClicked(evt);
            }
        });
        pnlDown.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 126, 150));

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        pnlDown.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txtFirstname.setText("Tri");
        pnlDown.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 227, -1));

        lblFirstname.setText("First name");
        pnlDown.add(lblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 71, -1));

        lblLastname.setText("Last name");
        pnlDown.add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 71, -1));

        txtLastname.setText("To Minh");
        pnlDown.add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 227, -1));

        lblAddress.setText("Address");
        pnlDown.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 71, -1));

        txtEmail.setText("abc@gmail.com");
        pnlDown.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 227, -1));

        txtPhone.setText("0844993847");
        pnlDown.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 157, 230, -1));

        lblPhone.setText("Phone");
        pnlDown.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 135, 71, -1));
        pnlDown.add(txtBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 230, -1));

        lblBirthday.setText("Birthday");
        pnlDown.add(lblBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 71, -1));

        genderGroup.add(rdoMale);
        rdoMale.setSelected(true);
        rdoMale.setText("Male");
        pnlDown.add(rdoMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        genderGroup.add(rdoFemale);
        rdoFemale.setText("Female");
        pnlDown.add(rdoFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        lblGender.setText("Gender");
        pnlDown.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 71, -1));

        btnNext.setBackground(new java.awt.Color(238, 0, 51));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("FINISH");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlDown.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 150, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        pnlDown.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 540, 80));

        lblEmail.setText("Email");
        pnlDown.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 71, -1));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlDown, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhotoMouseClicked
        choosePhoto();
    }//GEN-LAST:event_lblPhotoMouseClicked

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        choosePhoto();
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        insert();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupDetailsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupDetailsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupDetailsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupDetailsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignupDetailsJDialog dialog = new SignupDetailsJDialog(new javax.swing.JFrame(), true, omegaAccount);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblPersonalDetailTitle;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JPanel pnlDown;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlUp;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextArea txtAddress;
    private com.toedter.calendar.JDateChooser txtBirthday;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
